### PR TITLE
Improving create_cfm

### PR DESCRIPTION
**Pull request by oesteban**
I think we can remove the subtraction using ANTs tools and make it in pure python. Also, simplified the logic around this.

Please check manually this function (e.g. in an ipython notebook), passing the masks manually and checking that the outcomes are the intended.

### CODE REVIEW

**Comment by oesteban** [comment]
@chrisfilo could you have a quick look?

**Comment by oesteban** [comment]
@danlurie if you could share a dataset with a corresponding lesion mask, I'd be very happy to write a couple of tests for your changes (one test for `create_cfm` and one for the registration itself`).

**Comment by chrisgorgo** [comment]
Yeah that seems correct if I understand the intended logic correctly. Obviously @danlurie needs to test this so we could be sure.

**Comment by danlurie** [comment]
Testing the new cfm function now. @chrisfilo do you think @oesteban's method is preferable to the inversion+logical_and solution we came up with yesterday?

I've also just gone through the changes/merges we made yesterday. Turns out we had the logic backwards for global masking when explicit masking is enabled. I'll commit/push my changes later tonight if this fixes the CCFM failure. 

I'll see if it's possible to provide some sample data. May be easier to look for already public examples, as our data has privacy concerns in the current form.

**Comment by chrisgorgo** [comment]
On Fri, Aug 4, 2017 at 8:38 PM, Daniel Lurie <notifications@github.com>
wrote:

> Testing the new cfm function now. @chrisfilo
> <https://github.com/chrisfilo> do you think @oesteban
> <https://github.com/oesteban>'s method is preferable to the
> inversion+logical_and solution we came up with yesterday?
>
I think they achieve the same goal.

**Comment by danlurie** [comment]
I adapted @oesteban's method and added it to my fork manually. Test just finished and everything looks great; the new version matches the regression test I ran prior to merging on Thursday. I'm going to close this PR and we can continue discussion in on https://github.com/poldracklab/niworkflows/pull/121

**Pull request closed without merging**
